### GaussianNB :- https://www.youtube.com/watch?v=r1in0YNetG8 (When features values are continous)

In [130]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [131]:
## Rain predication data
df = pd.read_csv('weatherAUS.csv')

##Intenationally setting one column null 
df.at[9,"RainTomorrow"] = np.NaN
df[:12]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No
5,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0.0,No
6,2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,0.0,No
7,2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0.0,No
8,2008-12-09,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No,1.4,Yes
9,2008-12-10,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,Yes,0.0,NaN
10,2008-12-11,Albury,13.4,30.4,0.0,NaN,NaN,N,30.0,SSE,...,22.0,1011.8,1008.7,NaN,NaN,20.4,28.8,No,2.2,Yes
11,2008-12-12,Albury,15.9,21.7,2.2,NaN,NaN,NNE,31.0,NE,...,91.0,1010.5,1004.2,8.0,8.0,15.9,17.0,Yes,15.6,Yes

In [132]:
## Using few fields for predication and change nan value to 0 for feature and remove rows having label nan
df = df[["MinTemp","MaxTemp","Rainfall","WindGustDir","WindGustSpeed","Humidity3pm","RainTomorrow"]]
nanRainTomorrow = df.loc[df['RainTomorrow'].isnull()].shape
print("Size of data before formatting : {} and null row {}".format(df.shape,nanRainTomorrow))

## remove rows having label ("RainTomorrow") nan
df.dropna(subset=["RainTomorrow"],inplace=True)
nanRainTomorrow = df.loc[df['RainTomorrow'].isnull()].shape
print("Size of data after removing rows having label (RainTomorrow) nan : {} null row {}".format(df.shape,nanRainTomorrow))

## change nan value to 0 for feature
df.fillna(0,inplace=True)

Size of data before formatting : (145460, 7) and null row (3268, 7)
Size of data after removing rows having label (RainTomorrow) nan : (142192, 7) null row (0, 7)

In [133]:
## Naive Bayes need numeric values for feature. WindGustDir is string.
X_train = df[["MinTemp","MaxTemp","Rainfall","WindGustDir","WindGustSpeed","Humidity3pm"]].to_numpy();
print(X_train)
y_train = df["RainTomorrow"].to_numpy();
print(y_train)
GaussianNB().fit(X_train,y_train)

[[13.4 22.9 0.6 'W' 44.0 22.0]
 [7.4 25.1 0.0 'WNW' 44.0 25.0]
 [12.9 25.7 0.0 'WSW' 46.0 30.0]
 ...
 [3.6 25.3 0.0 'NNW' 22.0 21.0]
 [5.4 26.9 0.0 'N' 37.0 24.0]
 [7.8 27.0 0.0 'SE' 28.0 24.0]]
['No' 'No' 'No' ... 'No' 'No' 'No']

ValueError: could not convert string to float: 'W'

In [139]:
## converting string column to number using label encoder
from sklearn.preprocessing import LabelEncoder
WindGustDir = LabelEncoder().fit_transform(list(df["WindGustDir"]))
df["WindGustDir"] = WindGustDir
df[:10]

,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,Humidity3pm,RainTomorrow
0,13.4,22.9,0.6,14,44.0,22.0,No
1,7.4,25.1,0.0,15,44.0,25.0,No
2,12.9,25.7,0.0,16,46.0,30.0,No
3,9.2,28.0,0.0,5,24.0,16.0,No
4,17.5,32.3,1.0,14,41.0,33.0,No
5,14.6,29.7,0.2,15,56.0,23.0,No
6,14.3,25.0,0.0,14,50.0,19.0,No
7,7.7,26.7,0.0,14,35.0,19.0,No
8,9.7,31.9,0.0,7,80.0,9.0,Yes
10,13.4,30.4,0.0,4,30.0,22.0,Yes

In [143]:
X_train = df[["MinTemp","MaxTemp","Rainfall","WindGustDir","WindGustSpeed","Humidity3pm"]].to_numpy();
print(X_train)
y_train = df["RainTomorrow"].to_numpy();
print(y_train)
GaussianNB().fit(X_train,y_train)

[[13.4 22.9  0.6 14.  44.  22. ]
 [ 7.4 25.1  0.  15.  44.  25. ]
 [12.9 25.7  0.  16.  46.  30. ]
 ...
 [ 3.6 25.3  0.   7.  22.  21. ]
 [ 5.4 26.9  0.   4.  37.  24. ]
 [ 7.8 27.   0.  10.  28.  24. ]]
['No' 'No' 'No' ... 'No' 'No' 'No']

GaussianNB(priors=None, var_smoothing=1e-09)

In [192]:
from sklearn import preprocessing
X = np.float64([[2,3],[4,5],[6,7],[8,9],[10,11]])
print("Original X : \n",X)
# Generalize the data by making mean to 0 and variance to 1
sscaler = preprocessing.StandardScaler().fit_transform(X)
print("StandardScaler X : \n",sscaler)
print("Mean for first {} second {} column ".format(np.mean(sscaler[:,0]),np.mean(sscaler[:,1])))
print("Variance for first {} second {} column ".format(np.var(sscaler[:,0]),np.var(sscaler[:,1])))

Original X :
 [[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]
StandardScaler X :
 [[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]
Mean for first 0.0 second 0.0 column
Variance for first 0.9999999999999998 second 0.9999999999999998 column

In [194]:
# Generalize the data by keeping all values b/w 0 and 1. (x - xmin)/(xmax - xmin)
minMaxScaler = preprocessing.MinMaxScaler().fit_transform(X)
print("MinMaxScaler X : \n",minMaxScaler)

MinMaxScaler X :
 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]